### ISSUE TITLE
Update new token auction start/end mechanism 

### ISSUE THREAD

**Issue by ninjaahhh** [QuarkChain/quarkchain-contracts#12]
instead of explicitly calling start and end, we want to have a more autonomous approach

1. supervisor (could be DAO in the future) sets the parameters
1. the first bidder's action (`bid`) will automatically start the auction process, until `duration` is reached
1. once ended, a new bid or an explicit call to `end` the auction will finalize the results of last round of auction

**Comment by hanyunx** [comment]
Done.
