### ISSUE TITLE
WithdrawStake should require "amount > 0"

### ISSUE THREAD

**Issue by qizhou** [QuarkChain/quarkchain-contracts#16]
https://github.com/QuarkChain/quarkchain-contracts/blob/51a12058502b0fdf675772b8d5ae4c0841861dd0/contracts/StakingPool.sol#L58

If an attacker intentionally withdraw a 0 balance stake where the stake's address is not in the array, I think an unexpected result will happen

**Comment by ninjaahhh** [comment]
good catch. EVM will throw `VM error: invalid opcode.` and burn all the gas

**Comment by qizhou** [comment]
The revert case should happen when the staker list is empty.  However, if the list is not empty, withdrawing with 0 amount should remove the first staker info (as arrPos = 0).  We need a test to cover it.

**Comment by ninjaahhh** [comment]
I prefer to simply not allow withdrawing 0
