### ISSUE TITLE
Should apply max_staker <= 65535

### ISSUE THREAD

**Issue by qizhou** [QuarkChain/quarkchain-contracts#17]
https://github.com/QuarkChain/quarkchain-contracts/blob/51a12058502b0fdf675772b8d5ae4c0841861dd0/contracts/StakingPool.sol#L101

We use uint16 to enumerate all stakers, which is up to 65535, while maximum stakers is uint128

**Comment by ninjaahhh** [comment]
or we can use `uint128` for `i`?

**Comment by qizhou** [comment]
> or we can use `uint128` for `i`?

This could be another fix.
