### ISSUE TITLE
Suggest to use uint256 for stake field

### ISSUE THREAD

**Issue by qizhou** [QuarkChain/quarkchain-contracts#19]
https://github.com/QuarkChain/quarkchain-contracts/blob/51a12058502b0fdf675772b8d5ae4c0841861dd0/contracts/StakingPool.sol#L11

I see a lot of conversion from uint256 to uint128.  Although it should be generally safe to convert as we have up to 1e28 tokens (about 2**93), but the conversion will succeed even such conversion may result in data loss.

Notice that changing to uint256 will add extra gas cost to adding and withdrawing stakes (I think it is about 5000 or 20000).

**Comment by ninjaahhh** [comment]
the reason is for saving storage (and gas), as a struct with two uint128 (`StakerInfo`) fields will be packed into one 256-bit word, thus writing to it only costs 20000;  if it has two uint256 fields then writing will double the cost to 40000

since `calculatePayout` will already consume lots of gas due to the loop, I would suggest saving as much as we can

**Comment by qizhou** [comment]
> the reason is for saving storage (and gas), as a struct with two uint128 (`StakerInfo`) fields will be packed into one 256-bit word, thus writing to it only costs 20000; if it has two uint256 fields then writing will double the cost to 40000
> 
> since `calculatePayout` will already consume lots of gas due to the loop, I would suggest saving as much as we can

I understand that, but my argument is that calculatePayout() may not benefit from such optimization since it only read stakers field in the function.

**Comment by ninjaahhh** [comment]
ok that makes sense: packing uint128 won't help reduce the gas of `calculatePayout` function, but it helps reduce the gas when adding new stakers. since the latter is a far less common operation, it's fine to not optimize
