### ISSUE TITLE
Need endTime function or field

### ISSUE THREAD

**Issue by qizhou** [QuarkChain/quarkchain-contracts#23]
https://github.com/QuarkChain/quarkchain-contracts/blob/51a12058502b0fdf675772b8d5ae4c0841861dd0/contracts/NonReservedNativeTokenManager.sol#L77

The endTime calculation is repeatedly used in several places, and they should be either replaced by an internal function or a field in auction directly.

**Comment by hanyunx** [comment]
Function added.
