### ISSUE TITLE
endAuction() should address failed auction correctly

### ISSUE THREAD

**Issue by qizhou** [QuarkChain/quarkchain-contracts#26]
https://github.com/QuarkChain/quarkchain-contracts/blob/51a12058502b0fdf675772b8d5ae4c0841861dd0/contracts/NonReservedNativeTokenManager.sol#L124

Looks like the previous auction's owner will be overridden to address(0).

**Comment by hanyunx** [comment]
Since each round of auction can only be started by some bidder place a bid, there will not be the circumstance that no one appears in a round of auction except the initial round. The initial round can be addressed separately (See #34).
