### ISSUE TITLE
Reuse calculateGas() in payAsGas()

### ISSUE THREAD

**Issue by qizhou** [QuarkChain/quarkchain-contracts#31]
https://github.com/QuarkChain/quarkchain-contracts/blob/39a33175b123b1843c6272e491efcd5090bc55cc/contracts/GeneralNativeTokenManager.sol#L154

The logic is the same and we should reuse the logic.

**Comment by ninjaahhh** [comment]
is this done? @jyouyj

**Comment by jyouyj** [comment]
Update gas reserve calculation API #47
