### ISSUE TITLE
Unit of amount should be clarified

### ISSUE THREAD

**Issue by qizhou** [QuarkChain/quarkchain-contracts#32]
https://github.com/QuarkChain/quarkchain-contracts/blob/39a33175b123b1843c6272e491efcd5090bc55cc/contracts/GeneralNativeTokenManager.sol#L136

Looks like the amount parameter can be one of the following:
1, the native token amount, i.e., gasPrice * gasUsed (or  start)
2, the native token gasPrice.

If it works for both, I think we need to at least add one comment to clarify.

**Comment by ninjaahhh** [comment]
seems we need a comment to clarify the new gas price parameter @jyouyj

**Comment by jyouyj** [comment]
Update gas reserve calculation API #47

**Comment by ninjaahhh** [comment]
> seems we need a comment to clarify the new gas price parameter @jyouyj

I think the issue is to clarify the gas price argument
