### ISSUE TITLE
Testing scenario

### ISSUE THREAD

**Issue by ninjaahhh** [QuarkChain/quarkchain-contracts#4]
unit tests should be under `test` folder

for auctioning new tokens:

1. start an auction, one person bids, auction ends, he wins
1. start an auction, one person bids, another person bids with a lower price, should fail
1. start an auction, one person bids, another person outbids auction ends, the other guy wins
1. start an auction, one person bids, another person places a bid at last minute before end time, the auction is extended. When the auction ends, the last bidder wins.
1. (more to come)

for gas reserves:

1. first time adding reserve should succeed
1. adding more QKC to the reserve should succeed
1. another person requests to have a higher exchange rate, should succeed
1. another person requests to have a higher exchange rate, but doesn't have any QKC, should fail
1. (more to come)

for how to write contract tests, [this](https://github.com/QuarkChain/qkc-erc20-deposit/blob/master/test/TermDepositSimplified.test.js) is a working example

feel free to add other test cases
cc @qizhou

**Comment by hanyunx** [comment]
Test cases for withdraw deposit in token auction:
Bidder 1 places a bid, bidder 2 places another bid. 
1. Bidder 2 tries to withdraw, should fail. 
1. Bidder 1 then outbids, bidder 2 tries to withdraw, should success.

**Comment by ninjaahhh** [comment]
close for now
