### ISSUE TITLE
StakingPool: better to always use safe math 

### ISSUE THREAD

**Issue by freedostudio** [QuarkChain/quarkchain-contracts#83]
https://github.com/QuarkChain/quarkchain-contracts/blob/7a762f5e668c9806dc24a97f9f05ea8a069db9be/contracts/StakingPool.sol#L82
It is better to use safe math for all places like this

**Comment by qizhou** [comment]
@ninjaahhh How do you view this?   I notice there is a >= test on L81, but replace them with SafeMath can be more consistent.

**Comment by ninjaahhh** [comment]
yes its precondition has been checked at the line above.

afaik I've manually checked every arithmetic operation, but using safemath can give us more confidence
